use rest_asp_net_core;

CREATE TABLE `persons` (
	`Id` int(10) UNSIGNED NULL DEFAULT NULL,
	`FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
	`Address` VARCHAR(50) NULL DEFAULT NULL,
	`Gender` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB;

ALTER TABLE persons CHANGE Id Id int(10) AUTO_INCREMENT PRIMARY KEY;